### ISSUE TITLE
Test suite fails on i686

### ISSUE THREAD

**Issue by peti** [cpeikert/Lol#29]
Citing from http://hydra.nixos.org/build/49722958/nixlog/1/raw:

~~~~
running tests
Running 1 test suites...
Test suite test-lol-cpp: RUNNING...
Test suite test-lol-cpp: FAIL
Test suite logged to: dist/test/lol-cpp-0.0.0.3-test-lol-cpp.log
0 of 1 test suites (0 of 1 test cases) passed.
~~~~

**Comment by crockeea** [comment]
This doesn't surprise me in the slightest. I didn't write the CPP backend to be particularly platform-independent, mostly because I don't know how. Certainly lol-cpp requires at least simulation of 64-bit arithmetic. I hoped to avoid that issue by using `int64_t` from `inttypes.h`, but perhaps that didn't work. If you'd like to see this work for i686, we'd be happy to merge a pull request.
